url: "//joostop.github.io" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "github.io" # the subpath of your site, e.g. /blog
title: "Joost Opschoor" # title
description: "joost.opschoor [at] sam.math.ethz.ch" # subtitle
