menu:
- {name: 'Google Scholar', url: 'https://scholar.google.com/citations?user=vmMeSPUAAAAJ&hl=nl&oi=ao'}
- {name: 'Contact', url: 'https://math.ethz.ch/sam/the-institute/people.html?u=ojoost'}

social:
- {icon: 'linkedin', link: 'https://linkedin.com/in/joost-opschoor'}
